### ISSUE TITLE
I accidentally transfer my $3000 UNI to safemoon contract address

### ISSUE THREAD

**Issue by yangjiao80** [Safemoon-Protocol/Discord-Bot#20]
When I withdraw from MEXC for safemoon, I add safemoon contract address to my metamask to show the token, then I withdraw my UNI I accidentally paste the safemoon contract address, right now the transaction is done, can SAFEMOON please send my UNI back to me!!!
Thank you.

**Comment by yangjiao80** [comment]
I can provide the trasaction hash and all the info to the support!

**Comment by reecebenson** [comment]
Hi @yangjiao80, I'm not a member of the SafeMoon team but this question probably shouldn't be asked here. You'll have some better luck reaching out to the devs via the [Discord server](https://discord.gg/safemoon). Best of luck!
