### ISSUE TITLE
Dex Guru price error

### ISSUE THREAD

**Issue by GangstaDev** [Safemoon-Protocol/Discord-Bot#27]
Why does this error? Dex Gurus API returns data

**Comment by MikeTheShadow** [comment]
What is the error?

**Comment by GangstaDev** [comment]
> What is the error?

TypeError: Cannot read property 'price' of undefined
    at getPrice (C:\Users\bbbre\Desktop\Discord-Bot\src\utils\external.js:81:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getDexPrice (C:\Users\bbbre\Desktop\Discord-Bot\src\utils\external.js:24:12)
    at async C:\Users\bbbre\Desktop\Discord-Bot\src\jobs\pricewatch-single.js:32:39
    at async Object.run (C:\Users\bbbre\Desktop\Discord-Bot\src\jobs\pricewatch-single.js:20:5)


I'm trying to use it to get updates on a token that isnt on the pancake api tokens list yet

**Comment by reecebenson** [comment]
Hi @Tincon1,

If you're making any changes to the source code in this repository and encountering issues, please don't use the issues here to try and resolve the issues you've stumbled across or created yourself. The purpose of this repository is to raise issues around the current state of the master branch.

Cheers

**Comment by GangstaDev** [comment]
> Hi @Tincon1,
> 
> If you're making any changes to the source code in this repository and encountering issues, please don't use the issues here to try and resolve the issues you've stumbled across or created yourself. The purpose of this repository is to raise issues around the current state of the master branch.
> 
> Cheers

I've changed the contract address in the config, thats all not one piece of code was touched. I was just curious why the Dex Guru check wasnt working, as dex guru does infact provide the data
