### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by ketiaaa** [Safemoon-Protocol/Discord-Bot#3]
Its says invalid token, tried 3-4 different token and still doesnt work.

**Comment by mikavehns** [comment]
Its because he put DISCORD_TOKEN or sth like that instead of the real token. He cant leak the token or everyone could just make everything with the bot in the server.

**Comment by HankWyatt** [comment]
> 
> 
> Its because he put DISCORD_TOKEN or sth like that instead of the real token. He cant leak the token or everyone could just make everything with the bot in the server.

This ^. You must add your own .env file with your discord token listed in order for it to work correctly.
