### ISSUE TITLE
icons missing when running bot at private server

### ISSUE THREAD

**Issue by jimango** [Safemoon-Protocol/Discord-Bot#8]
I wonder if its possible to download the icons somewhere?

When running the command !price I get the output: :GreenSafu: 0.000002542 or :RedSafu:
I guess its because Im missing the icons at the server or I have given the bot wrong oath2 settings?

Help with this would really be appreaciated.

**Comment by reecebenson** [comment]
Hi @jimango,

You can add the `RedSafu` and `GreenSafu` emotes to your server by yourself. Just go to the SafeMoon server, type `:RedSafu:` and `:GreenSafu:`, right-click them and save the image. Go to your server settings and then Emojis, and upload them.

Hope this helps!

**Comment by jimango** [comment]
Thank you for the explination, but it still doesnt work

**Comment by jimango** [comment]
Could it be something wrong in the bot permissions?
Trying real hard to get my mind around this together with an other from the community.

**Comment by reecebenson** [comment]
Hi @jimango,

I'll raise some changes so that these icons are pulled from the guild the server is in if available, or default back to other global emojis to represent its state.

**Comment by jimango** [comment]
The positive with having only plain green and red is that its easier to integrate when using toward other coins as well.
Having it optional or maybe with using custom icons would be really nice.
